[package]
name = "mirage_interceptor"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mirage_schema = { workspace = true }
mirage_remote = { workspace = true }
mirage_uapi = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
mirage_real = { workspace = true }

