//! Build script — propagate the rocjitsu runtime library location into
//! this crate's binaries, tests, examples, and benches as an rpath.
//!
//! `rocjitsu_sys` exposes the directory containing `librocjitsu_kmd.so`
//! via the `links = "rocjitsu_kmd"` metadata key. Cargo forwards that
//! value to direct dependents as `DEP_ROCJITSU_KMD_LIB_DIR`. We read
//! it here and emit the `rustc-link-arg-*` directives that cargo
//! rejects when they come from a sys crate (sys crates have no bin /
//! test targets of their own).

use std::env;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=DEP_ROCJITSU_KMD_LIB_DIR");
    if let Ok(lib_dir) = env::var("DEP_ROCJITSU_KMD_LIB_DIR") {
        // `rustc-link-arg=` (without a target-kind suffix) applies to
        // every linked artifact the current crate produces — notably
        // the test binary generated by `cargo test`.
        println!("cargo:rustc-link-arg=-Wl,-rpath,{lib_dir}");
    }
}
