//! Raw FFI bindings for the [rocjitsu] C API, generated by [`bindgen`] at
//! build time from `rocjitsu/rocjitsu.h`.
//!
//! See [`build.rs`](../build.rs) for how headers and the companion
//! library are located.
//!
//! # Scope
//!
//! This crate is pure FFI: every symbol mirrors a C declaration
//! verbatim. Higher-level, safe wrappers live in sibling crates (for
//! example `mirage_rocjitsu`).
//!
//! [rocjitsu]: https://github.com/ROCm/rocm-systems/tree/main/experimental/rocjitsu

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]
#![allow(clippy::missing_safety_doc)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
