[workspace]
resolver = "3"
members = [".", "mirage_*", "rocjitsu_sys"]

[workspace.dependencies]
serde = { version = "1" }
serde_json = { version = "1" }
async-trait = { version = "0.1.89" }
paste = { version = "1" }
libc = { version = "0.2" }
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "io-util", "sync", "fs"] }

amdgpu_protocol = { path = "amdgpu_protocol" }
mirage_schema = { path = "mirage_schema" }
mirage_ctl = { path = "mirage_ctl" }
mirage_daemon = { path = "mirage_daemon" }
rocjitsu_sys = { path = "rocjitsu_sys" }
