[package]
name = "mirage_daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
mirage_container = { path = "../mirage_container" }
mirage_real = { path = "../mirage_real" }
mirage_remote = { path = "../mirage_remote" }
mirage_schema = { workspace = true }
tokio = { workspace = true }
