[package]
name = "mirage_uapi"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
doctest = false

[dependencies]
bytes = { workspace = true }
libc = { workspace = true }
paste = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
bindgen = "0.70"
