//! Raw `#[repr(C)]` Rust bindings for the Linux AMD KFD and DRM-AMDGPU
//! UAPIs, generated by [`bindgen`] at build time from:
//!
//! * `/usr/include/linux/kfd_ioctl.h`
//! * `/usr/include/drm/amdgpu_drm.h`
//!
//! Override either header path by setting `MIRAGE_UAPI_KFD_HEADER` or
//! `MIRAGE_UAPI_DRM_HEADER` in the environment.
//!
//! # What this crate is for
//!
//! The sibling crate `mirage_schema` defines **serde-native, transport-
//! friendly** Rust request/response types for each ioctl. Those types
//! never cross the kernel boundary. This crate defines the *raw* C
//! structs that *do* cross the kernel boundary — so that
//! `mirage_interceptor` can read an ioctl arg buffer, build the typed
//! `mirage_schema` request, receive a response, and write results back
//! into the same buffer without hand-rolling memory layout.
//!
//! # What it is **not**
//!
//! There is deliberately no `ioctl(2)` wrapper here: the raw call lives
//! in `mirage_real` for the host-forwarding case, and in
//! `mirage_interceptor` for the LD_PRELOAD hooks.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]

mod ioctl_macro;

pub mod amdgpu;
pub mod amdgpu_error;
pub mod drm_marshal;
pub mod ioctl;
pub mod kfd_marshal;
pub mod marshal;

pub use marshal::{FromC, FromCWith, ToBytes, ToC};

pub mod kfd {
    include!(concat!(env!("OUT_DIR"), "/kfd.rs"));
}

pub mod drm {
    include!(concat!(env!("OUT_DIR"), "/drm.rs"));
}

// ---------------------------------------------------------------------------
// Minimal helpers for `_IO*` decoding, so callers don't have to pull in
// an entire crate just to extract the ioctl nr and size.

pub mod ioc {
    //! Decode/encode bits of the Linux `_IOC` ioctl-number layout.

    pub const NRBITS: u32 = 8;
    pub const TYPEBITS: u32 = 8;
    pub const SIZEBITS: u32 = 14;
    pub const DIRBITS: u32 = 2;

    pub const NRSHIFT: u32 = 0;
    pub const TYPESHIFT: u32 = NRSHIFT + NRBITS;
    pub const SIZESHIFT: u32 = TYPESHIFT + TYPEBITS;
    pub const DIRSHIFT: u32 = SIZESHIFT + SIZEBITS;

    pub const NRMASK: u32 = (1 << NRBITS) - 1;
    pub const TYPEMASK: u32 = (1 << TYPEBITS) - 1;
    pub const SIZEMASK: u32 = (1 << SIZEBITS) - 1;

    pub const DIR_NONE: u32 = 0;
    pub const DIR_WRITE: u32 = 1;
    pub const DIR_READ: u32 = 2;

    #[inline]
    pub const fn nr(cmd: u32) -> u32 {
        (cmd >> NRSHIFT) & NRMASK
    }
    #[inline]
    pub const fn ty(cmd: u32) -> u32 {
        (cmd >> TYPESHIFT) & TYPEMASK
    }
    #[inline]
    pub const fn size(cmd: u32) -> u32 {
        (cmd >> SIZESHIFT) & SIZEMASK
    }
    #[inline]
    pub const fn iowr(ty: u32, nr: u32, size: u32) -> u32 {
        ((DIR_READ | DIR_WRITE) << DIRSHIFT)
            | (ty << TYPESHIFT)
            | (nr << NRSHIFT)
            | (size << SIZESHIFT)
    }
    #[inline]
    pub const fn iow(ty: u32, nr: u32, size: u32) -> u32 {
        (DIR_WRITE << DIRSHIFT) | (ty << TYPESHIFT) | (nr << NRSHIFT) | (size << SIZESHIFT)
    }
    #[inline]
    pub const fn ior(ty: u32, nr: u32, size: u32) -> u32 {
        (DIR_READ << DIRSHIFT) | (ty << TYPESHIFT) | (nr << NRSHIFT) | (size << SIZESHIFT)
    }

    /// Magic type byte for KFD ioctls (`'K'`).
    pub const KFD_MAGIC: u32 = b'K' as u32;
    /// Magic type byte for DRM ioctls (`'d'`).
    pub const DRM_MAGIC: u32 = b'd' as u32;
    /// Offset added to the raw DRM nr to yield an AMDGPU sub-command.
    pub const DRM_COMMAND_BASE: u32 = 0x40;
}
